### ISSUE TITLE
[BUG]: Nav hover state accessible?

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/civicactions.com#556]
**Expected behavior**
Nav link hover state to be accessible.

**Describe the bug**
I looks like the hover color on the nav is not accessible.

**To Reproduce**
List the steps to reproduce the bug:
1. Go to www.civicactions.com
2. Click on hover over nav links

**Add Screenshots**
Screenshots may help explain the problem.

**Desktop (what device and system were you using?):**
 - OS: Mac 10.14.5
 - Browser Firefox
<img width="1266" alt="Screen Shot 2019-06-11 at 10 58 39 AM" src="https://user-images.githubusercontent.com/1569463/59295500-ba1c8800-8c38-11e9-9be4-6634dc4697ef.png">

**Comment by zhelding** [comment]
No longer applicable. Blog link no longer in topnav. Closing issue.
