### ISSUE TITLE
[BUG]: Teams link doesn't work

### ISSUE THREAD

**Issue by jeffmaher** [CivicActions/civicactions.com#572]
Hey friends! Was looking up Bill's title for an intro, but the Team's link didn't work. 😿 

**Expected behavior**

A description of what you expected to happen.

**Describe the bug**

A description of what went wrong.

**To Reproduce**

1. Go to civicactions.com
2. Click on About (at top nav)
3. Click on Our Team (from menu)
4. See error (it's a 404 page, delivered from GitHub somewhat unexpectedly)

**Add Screenshots**

<img width="729" alt="Screen Shot 2019-07-15 at 21 15 28" src="https://user-images.githubusercontent.com/950486/61259029-58bf6b80-a746-11e9-829a-6ca67687d500.png">

**Desktop (what device and system were you using?):**

 - OS: macOs
 - Browser: Firefox
 - Version: 68.0

**Additional context**

Did a 30 second bounce around of other links in the nav and everything else worked.

P.S. Hope all is well!

**Comment by grugnog** [comment]
@jeffmaher hope you are well!! Thanks for the heads up - we hit a Let's Encrypt renewal issue and this was a temporary side effect while we figured that out :)
